name: Basic validation of examples

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Retrieve Python version to be used
      id: python_version_check
      run: echo ::set-output name=PYTHON_VERSION::$(cat tests/.python-version)
    - name: Install correct Python version
      uses: actions/setup-python@v2
      with:
        python-version: "${{ steps.python_version_check.outputs.PYTHON_VERSION }}"
    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('tests/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: pip install -r tests/requirements.txt
    - name: Verify examples/station_information.json
      run: jsonschema station_information.json -i examples/station_information.json
